# Generated by Django 5.1 on 2024-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
    ]
