# Generated by Django 5.1 on 2024-08-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furApp', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
