# Generated by Django 5.1 on 2024-08-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furApp', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='adoption_images/')),
                ('more_info', models.TextField()),
            ],
        ),
    ]
