# Generated by Django 5.1 on 2024-08-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furApp', '0005_adoptionprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdoptionProcess',
        ),
    ]
