# Generated by Django 5.1 on 2024-08-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furApp', '0006_delete_adoptionprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnMoreClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
