# Generated by Django 5.1 on 2024-08-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furApp', '0008_pet_adoption_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
