# Generated by Django 5.1 on 2024-08-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furApp', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
